name = "wms-industrial-cloudflare"
compatibility_date = "2025-08-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "wms-industrial-db"
database_id = "a287bf47-2f4c-4084-a70e-ade661c46ce4"
